CSVgenerator/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile/', RedirectView.as_view(url='/./scheme_list/', permanent=False)),
    path('', include('generator.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

generator/urls.py
from django.urls import path
from .views import (SchemeListView, SchemeCreateView, SchemeUpdateView, SchemeDeleteView, DatasetListView, 
            SchemeColumnCreateView, SchemeColumnUpdateView, SchemeColumnDeleteView, SchemeColumnListView, generate_csv)

urlpatterns = [
    path('scheme_list/', SchemeListView.as_view(), name='scheme-list'),
    path('scheme/add/', SchemeCreateView.as_view(), name='scheme-add'),
    path('scheme/<int:pk>/', SchemeUpdateView.as_view(), name='scheme-update'),
    path('scheme/<int:pk>/delete/', SchemeDeleteView.as_view(), name='scheme-delete'),

    path('scheme/column/list/<int:scheme__id>', SchemeColumnListView.as_view(), name='scheme-column-list'),
    path('scheme/column/add/', SchemeColumnCreateView.as_view(), name='scheme-column-add'),
    path('scheme/column/<int:pk>/', SchemeColumnUpdateView.as_view(), name='scheme-column-update'),
    path('scheme/column/<int:pk>/delete/', SchemeColumnDeleteView.as_view(), name='scheme-column-delete'),


    path('dataset_list/', DatasetListView.as_view(), name='dataset-list'),
    path('dataset/<int:pk>/generate/', generate_csv, name='generate-dataset'),
]

generator/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator


class Scheme(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    scheme_name = models.CharField(max_length=255, unique=True)

    min_age = models.IntegerField(default=0)
    max_age = models.IntegerField(default=100)
    quantity_of_sentences = models.IntegerField(default=1)

    rows = models.IntegerField(default=1)
    task_progress = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    upload = models.FileField(upload_to='', blank=True)

    def __str__(self):
        return self.scheme_name


class SchemeColumn(models.Model):
    CHOICES = (
    (1, 'Name'),
    (2, 'Job'),
    (3, 'Email'),
    (4, 'Domain'),
    (5, 'Phone number'),
    (6, 'Company'),
    (7, 'Text'),
    (8, 'Age'),
    (9, 'Address'),
    (10, 'Date')
    )

    scheme = models.ForeignKey(Scheme, on_delete=models.CASCADE)
    column_type = models.PositiveSmallIntegerField(choices=CHOICES, default=1)

    name = models.CharField(max_length=255, default="None")

    order = models.PositiveSmallIntegerField(default=1)

    class Meta:
        unique_together = ('scheme', 'order')

    def __str__(self):
        return self.name

generator/forms.py
from django import forms
from django.db import models
from .models import Scheme, SchemeColumn


class SchemeForm(forms.ModelForm):
    class Meta:
        model = Scheme
        fields = ['scheme_name', 'min_age', 'max_age', 'rows', 'quantity_of_sentences']


class SchemeColumnForm(forms.ModelForm):
    class Meta:
        model = SchemeColumn
        fields = ['column_type', 'name', 'order']

generator/views.py
import os

from django.shortcuts import render
from django.views.generic import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.http import Http404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.shortcuts import redirect
from django.contrib import messages
from django.conf import settings

from .models import Scheme, SchemeColumn
from .forms import SchemeForm, SchemeColumnForm
from .services import make_csv

@login_required
def generate_csv(request, *args, **kwargs):
    """
    calls a celery task and redirects to the same page
    """
    if request.POST:
        scheme_id = int(request.POST.get("scheme"))
        scheme = Scheme.objects.get(id=scheme_id)
        make_csv(scheme_id=scheme_id)
        return redirect('dataset-list')
    else:
        raise Http404()


@method_decorator(login_required, name='dispatch')
class SchemeListView(ListView):
    model = Scheme


@method_decorator(login_required, name='dispatch')
class DatasetListView(ListView):
    template_name = 'generator/dataset_list.html'
    model = Scheme


@method_decorator(login_required, name='dispatch')
class SchemeCreateView(CreateView):
	model = Scheme
	form_class = SchemeForm
	template_name = 'generator/scheme_create.html'
	success_url = '/scheme_list/'

	def form_valid(self, form):
		form.instance.author = self.request.user
		return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class SchemeUpdateView(UpdateView):
	model = Scheme
	form_class = SchemeForm
	template_name = 'generator/scheme_create.html'
	success_url = '/scheme_list/'

	def form_valid(self, form):
		form.instance.author = self.request.user
		return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class SchemeDeleteView(DeleteView):
	model = Scheme
	template_name = 'generator/scheme_confirm_delete.html'
	success_url = '/scheme_list/'


@method_decorator(login_required, name='dispatch')
class SchemeColumnCreateView(CreateView):
	model = SchemeColumn
	form_class = SchemeColumnForm
	template_name = 'generator/scheme_column_create.html'

	def form_valid(self, form):
		try:
			scheme_id = int(self.request.GET.get('scheme_id'))
			form.instance.scheme = Scheme.objects.get(id=scheme_id)
			return super().form_valid(form)
		except Exception:
			messages.error(self.request, f"Orders should be unique :(")
			return super().form_invalid(form)

	def get_success_url(self):
		return ''.join(('/scheme/', self.request.GET.get('scheme_id'), '/'))


@method_decorator(login_required, name='dispatch')
class SchemeColumnListView(ListView):
	template_name = 'generator/scheme_column_list.html'

	def get_queryset(self) :
		queryset = SchemeColumn.objects.filter(scheme=self.kwargs['scheme__id']).order_by('order')
		return queryset


@method_decorator(login_required, name='dispatch')
class SchemeColumnUpdateView(UpdateView):
	model = SchemeColumn
	form_class = SchemeColumnForm
	template_name = 'generator/scheme_column_create.html'

	def form_valid(self, form):
		scheme_id = int(self.request.GET.get('scheme_id'))
		form.instance.scheme = Scheme.objects.get(id=scheme_id)
		return super().form_valid(form)

	def get_success_url(self):
		return ''.join(('/scheme/', self.request.GET.get('scheme_id'), '/'))


@method_decorator(login_required, name='dispatch')
class SchemeColumnDeleteView(DeleteView):
	model = SchemeColumn
	template_name = 'generator/scheme_column_confirm_delete.html'

	def get_success_url(self):
		return ''.join(('/scheme/column/list/', str(self.kwargs['pk'])))

generator/templates/generator/base.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Обязательные метатеги -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <style>
    div {padding: 3px;}
    </style>
    <title>FakeCSV</title>
  </head>
  <body>
    {% include 'generator/navbar.html' %}
   <div  class="container">
        <div  class="row justify-content-center">
          {% block content %}
{% endblock %}
        </div>
    </div>
    


    <!-- Вариант 1: Bootstrap в связке с Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

  </body>
</html>

generator/templates/generator/dataset_list.html
{% extends 'generator/base.html' %}

{% block content %}
	<div class="row justify-content-md-center">
         <h3>Data Sets</h3>
 	</div>

	<div id='table'>
	<table class="table table-bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Created</th>
                    <th>Status</th>
                    <th>Actions</th>
                    <th>Generate</th>
                </tr>
            </thead>
            <tbody>
	            {% for scheme in object_list %}
	            <tr>
	            	<td>
	            		{{ scheme.pk }}
	            	</td>
	            	<td>
	            		{{ scheme.created }}
	            	</td>
	            	<td>
	            		{% if scheme.task_progress == 'Ready' %}
                		<div class="btn btn-success btn-sm">{{ scheme.task_progress }}</div>
            			{% else %}
                		<div class="btn btn-secondary btn-sm">{{ scheme.task_progress }}</div>
            			{% endif %}
	            	</td>
	            	<td>
	            		{% if scheme.task_progress == 'Ready' %}
	            		{% if scheme.upload %}
	            		<a href="{{ scheme.upload.url }}" download="{{ scheme.upload.url }}">Download</a>
	            		{% endif %}
	            		{% endif %}
	            	</td>
	            	<td>
	            	<form method="POST" action="{% url 'generate-dataset' scheme.pk %}">
                	{% csrf_token %}
                		<input type="hidden" name="scheme" value="{{ scheme.pk }}">
                		<input type="submit" class="btn btn-success btn-sm" value="Generate data">
        			</form>
	            	</td>
	            </tr>
	            {% endfor %}
	        </tbody>
	    </table>
	</div>
{% endblock %}

generator/templates/generator/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'scheme-list' %}"><strong></strong>FakeCSV</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'scheme-list' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'dataset-list' %}">Datasets</a>
        </li>
        <li class="nav-item">
          
        </li>
        <li class="nav-item">
            
            </li>
      </ul>
      <a class="nav-link" href="#">Hello, <b>{{user.username}}</b></a>
      &nbsp;
      <a class="nav-link" href="{% url 'logout' %}">Logout</a>
    </div>
  </div>
</nav>

generator/templates/generator/scheme_column_confirm_delete.html
{% extends 'generator/base.html' %}

{% block content %}
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Confirm delete</h3>
            </div>
            <div class="modal-body">
                <form action="" method="post">
                    {% csrf_token %}
                    <h5>
                        Are you sure you want to delete: <strong>Column {{ object }}</strong> ?
                    </h5>
                    <input  class="btn btn-danger" type="submit" value="Yes, I want to delete" />
                </form>
            </div>
            <div class="modal-footer">
                    <a class="btn btn-primary" href="{% url 'scheme-list' %}" role="button">Cancel</a>
            </div>
        </div>
    </div>
{% endblock %}

generator/templates/generator/scheme_column_create.html
{% extends 'generator/base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
    
          <div class="mb-3">
            <label for="id_column_type" class="form-label"> Type of data:</label>
            <p>{{ form.column_type }}</p>
            <label for="id_name" class="form-label"> Name :</label>
            <p>{{ form.name }}</p>
            <label for="id_rows" class="form-label"> Order :</label>
            <p>{{ form.order }}</p>
          </div>
          <input type="submit" class="btn btn-primary" value="Create Column">
        </form>
{% if messages %}
  <div>
      {% for message in messages %}
      <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>
          {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div class="alert alert-secondary" role="alert">
        {{ message }}
        </div>
        {% endif %}
      <p>
      {% endfor %}
  </div>
{% endif %}
{% endblock %}

generator/templates/generator/scheme_column_list.html
{% extends 'generator/base.html' %}

{% block content %}
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Order</th>
                    <th>Name</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
        		{% for column in object_list %}
        		<tr>
	            	<td>
	            		{{ column.order }}
	            	</td>
	            	<td>
	            		{{ column.name }}
	            	</td>
	            	<td>
	       				<a href ="{% url 'scheme-column-update' column.pk %}" class="btn btn-primary btn-sm">Edit column</a>
	            		&nbsp;
	            		<a href href ="{% url 'scheme-column-delete' column.pk %}" class="btn btn-danger btn-sm">Delete</a>

	            	</td>
	            </tr>
      
        {% endfor %}
    </tbody>
    <div class="col-12">
         <h3>Columns</h3>
    </div>

   
    
{% endblock %}

generator/templates/generator/scheme_confirm_delete.html
{% extends 'generator/base.html' %}

{% block content %}
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Confirm delete</h3>
            </div>
            <div class="modal-body">
                <form action="" method="post">
                    {% csrf_token %}
                    <h5>
                        Are you sure you want to delete: <strong>{{ scheme.schemename }}</strong> ?
                    </h5>
                    <input  class="btn btn-danger" type="submit" value="Yes, I want to delete" />
                </form>
            </div>
            <div class="modal-footer">
                    <a class="btn btn-primary" href="{% url 'scheme-list' %}" role="button">Cancel</a>
            </div>
        </div>
    </div>
{% endblock %}

generator/templates/generator/scheme_create.html
{% extends 'generator/base.html' %}

{% block content %}
        {% if object %}
    <div class="col-4">
    <form action="" method="post">
        {% csrf_token %}
          <div class="mb-3">
            <label for="id_scheme_name" class="form-label"> Scheme name :</label>
            <p>{{ form.scheme_name }}</p>
            <label for="id_rows" class="form-label"> Rows :</label>
            <p>{{ form.rows }}</p>
            <label for="id_rows" class="form-label"> Min age :</label>
            <p>{{ form.min_age }}</p>
            <label for="id_max_age" class="form-label"> Max age :</label>
            <p>{{ form.max_age }}</p>
            <label for="id_quantity_of_sentences" class="form-label"> How many sentences do you want to generate :</label>
            <p>{{ form.quantity_of_sentences }}</p>
          </div>
          <input type="submit" class="btn btn-primary" value="Create Scheme">
        </form>
    </div>
    <div class="col-8">
        <br>
         <div class="mb-3">
        <a href ="{% url 'scheme-column-list' object.id %}" class="btn btn-primary">Columns</a>
        </div>
        <div class="mb-3">
         <a class="btn btn-success" href="{%url 'scheme-column-add'%}?scheme_id={{ object.id }}" role="button">New Column</a>
         </div>
    </div>
      
        {% else %}
        <form action="" method="post">
        {% csrf_token %}
        <div class="col-12">
          <div class="mb-3">
            <label for="id_scheme_name" class="form-label"> Scheme name :</label>
            <p>{{ form.scheme_name }}</p>
            <label for="id_rows" class="form-label"> Rows :</label>
            <p>{{ form.rows }}</p>
            <label for="id_rows" class="form-label"> Min age :</label>
            <p>{{ form.min_age }}</p>
            <label for="id_max_age" class="form-label"> Max age :</label>
            <p>{{ form.max_age }}</p>
            <label for="id_quantity_of_sentences" class="form-label"> How many sentences do you want to generate :</label>
            <p>{{ form.quantity_of_sentences }}</p>
          </div>
        </div>
          <input type="submit" class="btn btn-primary" value="Create Scheme">
        </form>
        {% endif %}
{% endblock %}

generator/templates/generator/scheme_list.html
{% extends 'generator/base.html' %}

{% block content %}
	<div class="row col-12  justify-content-md-center">
    <div class="col-10">
         <h3>Data schemas</h3>
    </div>
    <div class="col-2">
      <a class="btn btn-success" href="{%url 'scheme-add'%}" role="button">New Schema</a>
    </div>
 </div>

	<table class="table table-bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Modified</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
	            {% for scheme in object_list %}
	            <tr>
	            	<td>
	            		{{ scheme.pk }}
	            	</td>
	            	<td>
	            		{{ scheme.scheme_name }}
	            	</td>
	            	<td>
	            		{{ scheme.modified }}
	            	</td>
	            	<td>
	            		<a href ="{% url 'scheme-update' scheme.pk %}" class="btn btn-primary btn-sm">Edit scheme</a>
	            		&nbsp;
	            		<a href ="{% url 'scheme-column-list' scheme.pk %}" class="btn btn-primary btn-sm">Columns</a>
	            		&nbsp;
	            		<a class="btn btn-success btn-sm" href="{%url 'scheme-column-add'%}?scheme_id={{ scheme.pk }}" role="button">New Column</a>
	            		&nbsp; 
	            		<a href ="{% url 'scheme-delete' scheme.pk %}" class="btn btn-danger btn-sm">Delete</a>

	            	</td>
	            </tr>
	            {% endfor %}
	        </tbody>

{% endblock %}